import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { GameProvider } from "./context/GameContext";


const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["400", "700"], 
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} `}>
        <GameProvider>

          {children}
        </GameProvider>
      </body>
    </html>
  );
}
